### ISSUE TITLE
Grammar issue

### ISSUE THREAD

**Issue by RichardLitt** [ecosyste-ms/home#234]
This string is everywhere: `dependency metadata many open source`. 

But it's not quite grammatical. Could we add an `of`? I'm not sure how to PR for this, as it's in multiple repos and repo descriptions. 

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/ecosyste-ms) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/ecosyste-ms/home/issues/234">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/ecosyste-ms/home/issues/234/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/ecosyste-ms/home/issues/234/pledge.svg">
</picture>
</a>

**Comment by andrew** [comment]
Thanks for reporting, I’ll do a find+replace across all the repos

**Comment by RichardLitt** [comment]
Great.

**Comment by andrew** [comment]
I believe I've updated it everywhere now, thanks again!

**Comment by RichardLitt** [comment]
Sweet.
